document.addEventListener("DOMContentLoaded", function () {

        // 1. Dynamic Header Live Clock
            function updateClock() {
                    const heading = document.getElementById("heading");
                            if (heading) {
                                        const now = new Date();
                                                    const timeString = now.toLocaleTimeString("en-US", {
                                                                    hour: "numeric",
                                                                                    minute: "2-digit",
                                                                                                    second: "2-digit",
                                                                                                                    hour12: true
                                                                                                                                });
                                                                                                                                            heading.innerText = timeString;
                                                                                                                                                    }
                                                                                                                                                        }
                                                                                                                                                            updateClock();
                                                                                                                                                                setInterval(updateClock, 1000);

                                                                                                                                                                    // 2. Dark/Light Theme Toggle
                                                                                                                                                                        const themeButton = document.getElementById("themeToggle");

                                                                                                                                                                            function applyTheme(theme) {
                                                                                                                                                                                    if (theme === "dark") {
                                                                                                                                                                                                document.body.classList.add("dark-mode");
                                                                                                                                                                                                            if (themeButton) themeButton.innerText = "Light Mode";
                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                document.body.classList.remove("dark-mode");
                                                                                                                                                                                                                                            if (themeButton) themeButton.innerText = "Dark Mode";
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                            let savedTheme = localStorage.getItem("theme") || "light";
                                                                                                                                                                                                                                                                applyTheme(savedTheme);

                                                                                                                                                                                                                                                                    if (themeButton) {
                                                                                                                                                                                                                                                                            themeButton.addEventListener("click", function () {
                                                                                                                                                                                                                                                                                        let isDark = document.body.classList.contains("dark-mode");
                                                                                                                                                                                                                                                                                                    let newTheme = isDark ? "light" : "dark";
                                                                                                                                                                                                                                                                                                                localStorage.setItem("theme", newTheme);
                                                                                                                                                                                                                                                                                                                            applyTheme(newTheme);
                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            // 3. Dynamic To-Do List
                                                                                                                                                                                                                                                                                                                                                const addTaskBtn = document.getElementById("addTask");
                                                                                                                                                                                                                                                                                                                                                    const taskInput = document.getElementById("taskInput");
                                                                                                                                                                                                                                                                                                                                                        const taskList = document.getElementById("taskList");

                                                                                                                                                                                                                                                                                                                                                            function addTask() {
                                                                                                                                                                                                                                                                                                                                                                    if (!taskInput || !taskList) return;
                                                                                                                                                                                                                                                                                                                                                                            let taskText = taskInput.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                    if (taskText === "") return;

                                                                                                                                                                                                                                                                                                                                                                                            let newTask = document.createElement("li");
                                                                                                                                                                                                                                                                                                                                                                                                    newTask.innerHTML = `<span>${taskText}</span> <button type="button" class="removeTask">Remove</button>`;

                                                                                                                                                                                                                                                                                                                                                                                                            taskList.appendChild(newTask);
                                                                                                                                                                                                                                                                                                                                                                                                                    taskInput.value = "";
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                            if (addTaskBtn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    addTaskBtn.addEventListener("click", addTask);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            if (taskInput) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    taskInput.addEventListener("keydown", function (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (e.key === "Enter") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                addTask();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (taskList) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    taskList.addEventListener("click", function (event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (event.target.classList.contains("removeTask")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                event.target.parentElement.remove();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 4. Keyboard Shortcut ('b' toggles background color)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.addEventListener("keydown", function (event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (event.key.toLowerCase() === "b") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.body.classList.toggle("blue-bg");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 5. Contact Form Validation & Email Sent Modal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const contactForm = document.getElementById("contactForm");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const modal = document.getElementById("modal");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const modalMessage = document.getElementById("modalMessage");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const closeModal = document.getElementById("closeModal");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (contactForm) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            contactForm.addEventListener("submit", function (event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        event.preventDefault();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let nameInput = document.getElementById("name");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let emailInput = document.getElementById("email");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let messageInput = document.getElementById("message");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let name = nameInput ? nameInput.value.trim() : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let email = emailInput ? emailInput.value.trim() : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let message = messageInput ? messageInput.value.trim() : "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!name || !email || !message) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (modalMessage) modalMessage.innerText = "Please fill out all required fields.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (!email.includes("@") || !email.includes(".")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (modalMessage) modalMessage.innerText = "Please enter a valid email address.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (modalMessage) modalMessage.innerText = "Email sent successfully!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    contactForm.reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (modal) modal.style.display = "block";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (closeModal) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    closeModal.addEventListener("click", function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (modal) modal.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                window.addEventListener("click", function (event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (modal && event.target === modal) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    modal.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
